Adding HSDP-1D to the Device List
techcompliant/TC-Specs pull request #18
Opened 2016-05-23 21:28 UTC by Vaasref

The simplest and less expensive (by no mean cheap) printer from the company specialized in e-warfare, SlapDragon.

The speed is not defined yet. But preliminary concept was 0.5 page/s with 40 lines/page.

The Device ID ans Device Type are also not defined since there is no corresponding type yet.

2016-05-24 17:20 UTC, andyleap commented
20 lines per second is crazy fast.  I would think something like 1~2 lines a second would be good.  There should also be some mention of the fact that a spark printer will require specialized paper, most likely black paper with a very thin layer of aluminum.

2016-05-24 18:21 UTC, sctjkc01 commented
You might wish to consider putting the HSDP in the [device list](TC-IDs.md) as well...

2016-05-25 10:01 UTC, Vaasref commented
@andyleap :andyleap The whole purpose of the printer is to dump data.

It needs to be fast to be able to do real time data logging.
If it can't be fast enough then it can't be SlapDragon since SlapDragon would not design a product for something else than e-war.

So if you are talking about black paper, I assume you looked at printing technologies. then you would also have seen that 20 lines/s is realistic.

Of course using sparks to print will come with high power consumption and EM sig.

2016-05-25 12:29 UTC, andyleap commented
No, 20 lines/s is not realistic.   Not for in game, just barely for real life.  If you were talking impact printer, you might have a chance, but while a high speed modern line printer could do up to 2000 lines per minute, putting that kind of thing into the game is insane.  Not to mention that every example of spark printers that I've seen is sitting at a line per second or so.  If you are wanting to log data, I would suggest going with something that's actually meant to be a storage device.

2016-05-25 15:41 UTC, Vaasref commented
What is sheet of paper if not a storage device ?

With the storage capacity of current HDD you can't beat the paper.
With 3MiB for every 1000pages in text mode.

And paper is a pain to hack into btw. Good luck trying to destroy records remotely, but if you want to access data you need a miracle.

I can still revert to simple line matrix if that really bugs you.

2016-05-25 16:22 UTC, andyleap commented
Paper is not a storage device, it's a static output device.  And I said impact, not line printer, as an impact printer does match up with what you are describing, and can be very fast..  Plus, what's the point of outputting 20 lines per second when you can't even read that fast?  Are you planning on putting a scanner in the game too?

2016-05-26 00:57 UTC, Vaasref commented
The point of logging is logging. You don't need to read logs as fast as it come.
If you have a sensor that does not work with magic, your need to log things.

And with a printer you don't need to manually remove te paper from it to make it hack safe.

You do with a floppies.
Also floppies are vulnerable to dus, heat, EM attacks, solar flares and they cannot be read by humans.
Floppies are a poor choice for security.


Paper is a storage media, when you write something on paper you are storing data on it. It's the whole point of paper.

And for that kind of purpose it's the best.

2016-05-26 02:15 UTC, sctjkc01 commented
If we’re listing the fallacies of floppies, might I just point out that paper...
* Is not too good with heat (too much and it’ll ignite).
  * Is a fire hazard.
* Is not too good with water (too much and it’s soggy, turning into a mushy pulp).
* Is insecure to attacks with the visible spectrum (can be read by literally _anyone_).
* Requires light to read (cannot be read in the dark).
* Requires a human to transfer information back into a computer.
* Can only be used once (print something on it, and that surface can't be used again).

2016-07-04 15:11 UTC, paultech commented
This got a bit out of hand

Changes needed to merge:
TC-IDs.md needs updated with a printer type
The speed of the printer needs to be decreased 5 lines/second is in range for me.

2016-10-07 14:22 UTC, andyleap requested changes
Also need to insert the printing speed into the spec as well.

2016-10-07 14:22 UTC, andyleap commented on HSDP-1D.md
> +speed of the line matrix and the lack of nedd for ink of a spark printer design will
"lack of nedd for ink" need*

2016-10-07 14:22 UTC, andyleap commented on HSDP-1D.md
> +speed !
Space between word and punctuation

2016-10-07 14:22 UTC, andyleap commented on HSDP-1D.md
> +The HSDP-1D is a Data version of the model 1, equiped with curring edge memory chips
"equiped with curring edge memory" equipped* cutting*

2016-10-07 14:22 UTC, andyleap commented on HSDP-1D.md
> +and buses this printer will be able to log everything you throw at it.
"and buses this" busses*

2016-10-07 14:22 UTC, andyleap commented on HSDP-1D.md
> +typesettings possibilities of the Graph variant.
"and lack typesettings possibilities" -> "and lacks the typesetting possibilities"

2016-10-07 14:22 UTC, andyleap commented on HSDP-1D.md
> +    Reads and prints the full memory of the DCPU halting
halting what?  halting the DCPU while the dump is running?

2016-10-07 14:22 UTC, andyleap commented on HSDP-1D.md
> +Printing more than 2048 bytes of data may in 1 interupt result in halting your DCPU.
"Printing more than 2048 bytes of data may in 1 interupt result in halting your DCPU." -> "Printing more than 2048 bytes of data in one interrupt may result in the DCPU halting until the printer can catch up."  May want to clear this up some, what about 2 back to back interrupts 1ms apart with 2048 bytes apiece?  Why isn't this buffer length listed anywhere else?

2016-10-07 14:22 UTC, andyleap commented on HSDP-1D.md
> +3 : Print simple line
simple or single?

2016-10-07 14:22 UTC, andyleap commented on HSDP-1D.md
> +```
Is there some reason this entire spec is a code block in markdown?  Makes it miss out on the formatting that could be happening.

2016-10-07 14:22 UTC, andyleap commented on HSDP-1D.md
> +The HSDP line is all about printing as fast as possible the data you need.
Phrasing awkward? maybe "The HSDP line is all about printing the data you need as fast as possible ."?

2016-10-07 14:22 UTC, andyleap commented on HSDP-1D.md
> +The HSDP offer you the best way to store you data in term of cost efficency.
"store you data in term of cost efficency" -> "store your data in terms of cost efficiency"

2016-10-07 14:22 UTC, andyleap commented on HSDP-1D.md
> +Paper power and data is all you need to run a HSDP, its clever design combining the
"Paper, power, and data are all you need" "it's"

2016-10-07 14:22 UTC, andyleap commented on HSDP-1D.md
> +But be reassured that no printer of the HSDP line can suffer from any amount of data
"But be assured"

2017-01-23 18:38 UTC, paultech commented
superseded by #34

2017-01-23 18:38 UTC, closed without merging