Add a real wall-clock time device
techcompliant/TC-Specs pull request #21
Opened 2016-08-21 19:23 UTC by shepheb

Comments welcome!

Is millisecond precision practical for the server's point of view?

2016-08-21 21:00 UTC, azertyfun commented
* Is the time UTC or dependent on the server local time? Or is it some in-game arbitrary time?
* Why 12 hours clock? Without even an am/pm indicator, that is pretty ambiguous.
* Milliseconds seems weird ; the generic clock only ticks at 60 Hz, and the DCPU is clocked at 100 KHz. Expecting such a level of accuracy from a mere clock in-game would be like expecting accuracy to the nanosecond in a clock today.

2016-08-22 12:09 UTC, shepheb commented
- I hadn't thought about time zones. Earth time zones don't make sense in a space travel game. Presumably there's some kind of universal time. I'd say for in-game it's that time. For other emulators, the host machine's local time seems fine to me.
- Unclear wording - it's in the range 0-23. I was just commenting that 12 was noon. I'll clarify that.
- By "wall clock" I don't mean that this is hardware driving an actual wall clock. It's just a euphemism for "absolute time and date". This is a computer's relatively fast view of time. That said, most hardware today has clock speeds in excess of 1 GHz (10000x faster than DCPU) and can track the time in microseconds (1000x more resolution than I'm proposing here). Reducing it to 100ths or 10ths of seconds would be fine with me, but I don't think a millisecond-accurate clock is out of place with the speed or supposed era of this hardware.

On another point, one of the reasons for this hardware is not the time or date exactly, but using the time and date (especially its high-resolution parts!) as entropy for a software PRNG. The lower the resolution of this clock, the harder that becomes.

2016-08-22 18:08 UTC, shepheb commented
I've updated this. Now it's a backwards-compatible extension to the generic clock device, which now combines relative timer and absolute time/date functions.

I've also clarified that the time zone is not specified. Interpreting the hardware time is a software concern, just as it is on present-day hardware. It's recommended, but not required, that emulators use the host machine's local time.

2016-08-25 03:39 UTC, ike709 commented on CPU/clock.md
> +- 'Y': Seconds; 0-59
`

2016-10-07 01:35 UTC, paultech approved these changes

2016-10-07 01:35 UTC, paultech commented
This looks good to me. Waiting on @andyleap to weight on then we will merge and get it into the emulator/client.

2016-10-07 01:50 UTC, andyleap requested changes
Strike the frame of reference bit, maybe replace it with something about "Your RTC may not come preset, please set time on first use" or something.

2016-10-07 01:50 UTC, andyleap commented on CPU/clock.md
> +In a game universe, the clock might start uninitialized (all 0s) and need to be
Specs are supposed to be written as if the spec is for a "real thing", i.e. In Character.  Referencing emulators and game universe is a no-no

2016-10-07 12:20 UTC, shepheb commented on CPU/clock.md
> +In a game universe, the clock might start uninitialized (all 0s) and need to be
Fixed. Now in-character, with mention that batteries to hold the time without power are recommended, but not required.

I struck the bit about "frame of reference" - it was referring to time zones originally, but that doesn't make sense in character.

2016-10-07 13:51 UTC, andyleap approved these changes

2016-10-07 13:55 UTC, merged

2016-10-07 13:55 UTC, Yamakaky commented
wrong indent, check the rendered version

2016-10-07 14:00 UTC, Yamakaky commented on CPU/clock.md
>   	- C: Number of ticks since last call in C
The phrase could be improved

2016-10-07 14:00 UTC, Yamakaky commented on CPU/clock.md
>   	- B: Clock is set to 60/B per second. Set B to zero to disable.
Clock tick rate is set...

2016-10-07 14:00 UTC, Yamakaky commented on CPU/clock.md
> +All interrupts return the real time in the same format:
Not clear, at first I thought the spec didn't define how the time is returned